### ISSUE TITLE
MimicJointPlugin is not loaded by the mimic_joint_plugin_gazebo macro when launched within a namespace

### ISSUE THREAD

**Issue by alonzolopez** [mintar/mimic_joint_gazebo_tutorial#1]
Using the mimic joint plugin in a namespace does not work with the mimic_joint_plugin_gazebo macro, and I believe it is because of how the robot_namespace is handled in the macro in mimic_joint_gazebo_tutorial.urdf.xacro

On line 44 and line 54 of mimic_joint_gazebo_tutorial.urdf.xacro, the namespace is handled by the following line:
`<robotNamespace>($robot_namespace)</robotNamespace>`

Should this be formatted as below instead?
`<robotNamespace>${robot_namespace}</robotNamespace>`

I made this change on my own version of the macro and can now use it within a robot_namespace. Previously the plugin was not loading.

**Comment by mintar** [comment]
Sorry for the late reply! Thanks for pointing out the bug - I've fixed it.
